### ISSUE TITLE
SimpleCounter doesn't update Text when Counter changed

### ISSUE THREAD

**Issue by laicasaane** [codewriter-packages/UniMob.UI-Samples#1]
I run the SimpleCounter sample but found that the change on Counter doesn't invoke the change on Text component. I don't really understand why.

**Comment by vanifatovvlad** [comment]
The SimpleCounter sample didn't work due to a bug in the library. i fixed it in UniMob.UI v0.4.5+

**Comment by laicasaane** [comment]
@vanifatovvlad Am I mistaking but I can't find v0.4.5.

**Comment by vanifatovvlad** [comment]
Just upgrade to the latest versions from the master branches
```
"com.codewriter.unimob": "https://github.com/codewriter-packages/UniMob.git#master",
"com.codewriter.unimob.ui": "https://github.com/codewriter-packages/UniMob.UI.git#master",
```

**Comment by laicasaane** [comment]
My bad. Thank you, it works perfectly well now! But would you mind release the tag so OpenUPM will update the package registry?
